<template>
    <div id="network_container" ref="container" ></div>
</template>

<script>
import { Network } from 'vis-network/standalone';
import { DataSet } from 'vis-data/standalone';
export default {
    data() {
        return {
            nodes: new DataSet([
                {
                    color: "#004e64",
                    font: { color: "white", size: "2rem" },
                    id: "start",
                    label: "start",
                    shape: "dot",
                    size: 100,
                    title:
                        "start Neighbors:\u003cbr\u003epublic_transport_train\u003cbr\u003ewalk\u003cbr\u003ecar\u003cbr\u003ebicycle\u003cbr\u003eship\u003cbr\u003epublic_transport_bus",
                    value: 6,
                },
                {
                    color: "#00a5cf",
                    font: { color: "white" },
                    id: "walk",
                    label: "walk",
                    shape: "dot",
                    size: 100,
                    title:
                        "walk Neighbors:\u003cbr\u003epublic_transport_train\u003cbr\u003epublic_transport_change\u003cbr\u003ewalk\u003cbr\u003ecar\u003cbr\u003epublic_transport_bus\u003cbr\u003ebicycle\u003cbr\u003eend\u003cbr\u003estationary",
                    value: 8,
                },
                {
                    color: "#9fffcb",
                    font: { color: "white" },
                    id: "bicycle",
                    label: "bicycle",
                    shape: "dot",
                    size: 100,
                    title:
                        "bicycle Neighbors:\u003cbr\u003ewalk\u003cbr\u003ecar\u003cbr\u003ebicycle\u003cbr\u003eend\u003cbr\u003estationary",
                    value: 5,
                },
                {
                    color: "#25a18e",
                    font: { color: "white" },
                    id: "public_transport_train",
                    label: "public_transport_train",
                    shape: "dot",
                    size: 100,
                    title:
                        "public_transport_train Neighbors:\u003cbr\u003epublic_transport_train\u003cbr\u003epublic_transport_change\u003cbr\u003ewalk\u003cbr\u003epublic_transport_bus\u003cbr\u003ebicycle\u003cbr\u003eend\u003cbr\u003estationary",
                    value: 7,
                },
                {
                    color: "#7ae582",
                    font: { color: "white" },
                    id: "car",
                    label: "car",
                    shape: "dot",
                    size: 100,
                    title:
                        "car Neighbors:\u003cbr\u003ecar\u003cbr\u003eend\u003cbr\u003estationary\u003cbr\u003ewalk",
                    value: 4,
                },
                {
                    color: "#25a18e",
                    font: { color: "white" },
                    id: "public_transport_bus",
                    label: "public_transport_bus",
                    shape: "dot",
                    size: 100,
                    title:
                        "public_transport_bus Neighbors:\u003cbr\u003epublic_transport_train\u003cbr\u003epublic_transport_change\u003cbr\u003ewalk\u003cbr\u003eend\u003cbr\u003epublic_transport_bus",
                    value: 5,
                },
                {
                    color: "#25a18e",
                    font: { color: "white" },
                    id: "ship",
                    label: "ship",
                    shape: "dot",
                    size: 100,
                    title: "ship Neighbors:\u003cbr\u003eend",
                    value: 1,
                },
                {
                    color: "#004e64",
                    font: { color: "white" },
                    id: "end",
                    label: "end",
                    shape: "dot",
                    size: 100,
                    title: "end Neighbors:\u003cbr\u003e",
                    value: 0,
                },
                {
                    color: "#004e64",
                    font: { color: "white" },
                    id: "stationary",
                    label: "stationary",
                    shape: "dot",
                    size: 100,
                    title:
                        "stationary Neighbors:\u003cbr\u003epublic_transport_train\u003cbr\u003epublic_transport_bus\u003cbr\u003ewalk\u003cbr\u003ecar\u003cbr\u003ebicycle\u003cbr\u003eend\u003cbr\u003estationary",
                    value: 7,
                },
                {
                    color: "#25a18e",
                    font: { color: "white" },
                    id: "public_transport_change",
                    label: "public_transport_change",
                    shape: "dot",
                    size: 100,
                    title:
                        "public_transport_change Neighbors:\u003cbr\u003epublic_transport_train\u003cbr\u003epublic_transport_bus\u003cbr\u003eend",
                    value: 3,
                },
            ]),
            edges: new DataSet([
                {
                    arrows: "to",
                    arrowstyle: "simple",
                    connectionstyle: "arc3,rad=0.1",
                    from: "start",
                    to: "walk",
                    value: 319,
                    weight: 1,
                },
                {
                    arrows: "to",
                    arrowstyle: "simple",
                    connectionstyle: "arc3,rad=0.1",
                    from: "start",
                    to: "bicycle",
                    value: 108,
                    weight: 1,
                },
                {
                    arrows: "to",
                    arrowstyle: "simple",
                    connectionstyle: "arc3,rad=0.1",
                    from: "start",
                    to: "public_transport_train",
                    value: 9,
                    weight: 1,
                },
                {
                    arrows: "to",
                    arrowstyle: "simple",
                    connectionstyle: "arc3,rad=0.1",
                    from: "start",
                    to: "car",
                    value: 92,
                    weight: 1,
                },
                {
                    arrows: "to",
                    arrowstyle: "simple",
                    connectionstyle: "arc3,rad=0.1",
                    from: "start",
                    to: "public_transport_bus",
                    value: 1,
                    weight: 1,
                },
                {
                    arrows: "to",
                    arrowstyle: "simple",
                    connectionstyle: "arc3,rad=0.1",
                    from: "start",
                    to: "ship",
                    value: 1,
                    weight: 1,
                },
                {
                    arrows: "to",
                    arrowstyle: "simple",
                    connectionstyle: "arc3,rad=0.1",
                    from: "walk",
                    to: "car",
                    value: 127,
                    weight: 1,
                },
                {
                    arrows: "to",
                    arrowstyle: "simple",
                    connectionstyle: "arc3,rad=0.1",
                    from: "walk",
                    to: "end",
                    value: 339,
                    weight: 1,
                },
                {
                    arrows: "to",
                    arrowstyle: "simple",
                    connectionstyle: "arc3,rad=0.1",
                    from: "walk",
                    to: "walk",
                    value: 155,
                    weight: 1,
                },
                {
                    arrows: "to",
                    arrowstyle: "simple",
                    connectionstyle: "arc3,rad=0.1",
                    from: "walk",
                    to: "bicycle",
                    value: 113,
                    weight: 1,
                },
                {
                    arrows: "to",
                    arrowstyle: "simple",
                    connectionstyle: "arc3,rad=0.1",
                    from: "walk",
                    to: "stationary",
                    value: 152,
                    weight: 1,
                },
                {
                    arrows: "to",
                    arrowstyle: "simple",
                    connectionstyle: "arc3,rad=0.1",
                    from: "walk",
                    to: "public_transport_train",
                    value: 39,
                    weight: 1,
                },
                {
                    arrows: "to",
                    arrowstyle: "simple",
                    connectionstyle: "arc3,rad=0.1",
                    from: "walk",
                    to: "public_transport_change",
                    value: 1,
                    weight: 1,
                },
                {
                    arrows: "to",
                    arrowstyle: "simple",
                    connectionstyle: "arc3,rad=0.1",
                    from: "walk",
                    to: "public_transport_bus",
                    value: 6,
                    weight: 1,
                },
                {
                    arrows: "to",
                    arrowstyle: "simple",
                    connectionstyle: "arc3,rad=0.1",
                    from: "car",
                    to: "walk",
                    value: 139,
                    weight: 1,
                },
                {
                    arrows: "to",
                    arrowstyle: "simple",
                    connectionstyle: "arc3,rad=0.1",
                    from: "car",
                    to: "car",
                    value: 33,
                    weight: 1,
                },
                {
                    arrows: "to",
                    arrowstyle: "simple",
                    connectionstyle: "arc3,rad=0.1",
                    from: "car",
                    to: "end",
                    value: 87,
                    weight: 1,
                },
                {
                    arrows: "to",
                    arrowstyle: "simple",
                    connectionstyle: "arc3,rad=0.1",
                    from: "car",
                    to: "stationary",
                    value: 39,
                    weight: 1,
                },
                {
                    arrows: "to",
                    arrowstyle: "simple",
                    connectionstyle: "arc3,rad=0.1",
                    from: "bicycle",
                    to: "bicycle",
                    value: 84,
                    weight: 1,
                },
                {
                    arrows: "to",
                    arrowstyle: "simple",
                    connectionstyle: "arc3,rad=0.1",
                    from: "bicycle",
                    to: "walk",
                    value: 124,
                    weight: 1,
                },
                {
                    arrows: "to",
                    arrowstyle: "simple",
                    connectionstyle: "arc3,rad=0.1",
                    from: "bicycle",
                    to: "stationary",
                    value: 44,
                    weight: 1,
                },
                {
                    arrows: "to",
                    arrowstyle: "simple",
                    connectionstyle: "arc3,rad=0.1",
                    from: "bicycle",
                    to: "end",
                    value: 95,
                    weight: 1,
                },
                {
                    arrows: "to",
                    arrowstyle: "simple",
                    connectionstyle: "arc3,rad=0.1",
                    from: "bicycle",
                    to: "car",
                    value: 2,
                    weight: 1,
                },
                {
                    arrows: "to",
                    arrowstyle: "simple",
                    connectionstyle: "arc3,rad=0.1",
                    from: "stationary",
                    to: "stationary",
                    value: 64,
                    weight: 1,
                },
                {
                    arrows: "to",
                    arrowstyle: "simple",
                    connectionstyle: "arc3,rad=0.1",
                    from: "stationary",
                    to: "walk",
                    value: 133,
                    weight: 1,
                },
                {
                    arrows: "to",
                    arrowstyle: "simple",
                    connectionstyle: "arc3,rad=0.1",
                    from: "stationary",
                    to: "public_transport_train",
                    value: 12,
                    weight: 1,
                },
                {
                    arrows: "to",
                    arrowstyle: "simple",
                    connectionstyle: "arc3,rad=0.1",
                    from: "stationary",
                    to: "bicycle",
                    value: 42,
                    weight: 1,
                },
                {
                    arrows: "to",
                    arrowstyle: "simple",
                    connectionstyle: "arc3,rad=0.1",
                    from: "stationary",
                    to: "car",
                    value: 43,
                    weight: 1,
                },
                {
                    arrows: "to",
                    arrowstyle: "simple",
                    connectionstyle: "arc3,rad=0.1",
                    from: "stationary",
                    to: "end",
                    value: 2,
                    weight: 1,
                },
                {
                    arrows: "to",
                    arrowstyle: "simple",
                    connectionstyle: "arc3,rad=0.1",
                    from: "stationary",
                    to: "public_transport_bus",
                    value: 4,
                    weight: 1,
                },
                {
                    arrows: "to",
                    arrowstyle: "simple",
                    connectionstyle: "arc3,rad=0.1",
                    from: "public_transport_train",
                    to: "walk",
                    value: 53,
                    weight: 1,
                },
                {
                    arrows: "to",
                    arrowstyle: "simple",
                    connectionstyle: "arc3,rad=0.1",
                    from: "public_transport_train",
                    to: "stationary",
                    value: 2,
                    weight: 1,
                },
                {
                    arrows: "to",
                    arrowstyle: "simple",
                    connectionstyle: "arc3,rad=0.1",
                    from: "public_transport_train",
                    to: "public_transport_change",
                    value: 11,
                    weight: 1,
                },
                {
                    arrows: "to",
                    arrowstyle: "simple",
                    connectionstyle: "arc3,rad=0.1",
                    from: "public_transport_train",
                    to: "bicycle",
                    value: 1,
                    weight: 1,
                },
                {
                    arrows: "to",
                    arrowstyle: "simple",
                    connectionstyle: "arc3,rad=0.1",
                    from: "public_transport_train",
                    to: "public_transport_train",
                    value: 2,
                    weight: 1,
                },
                {
                    arrows: "to",
                    arrowstyle: "simple",
                    connectionstyle: "arc3,rad=0.1",
                    from: "public_transport_train",
                    to: "end",
                    value: 3,
                    weight: 1,
                },
                {
                    arrows: "to",
                    arrowstyle: "simple",
                    connectionstyle: "arc3,rad=0.1",
                    from: "public_transport_train",
                    to: "public_transport_bus",
                    value: 1,
                    weight: 1,
                },
                {
                    arrows: "to",
                    arrowstyle: "simple",
                    connectionstyle: "arc3,rad=0.1",
                    from: "public_transport_change",
                    to: "public_transport_train",
                    value: 11,
                    weight: 1,
                },
                {
                    arrows: "to",
                    arrowstyle: "simple",
                    connectionstyle: "arc3,rad=0.1",
                    from: "public_transport_change",
                    to: "public_transport_bus",
                    value: 1,
                    weight: 1,
                },
                {
                    arrows: "to",
                    arrowstyle: "simple",
                    connectionstyle: "arc3,rad=0.1",
                    from: "public_transport_change",
                    to: "end",
                    value: 1,
                    weight: 1,
                },
                {
                    arrows: "to",
                    arrowstyle: "simple",
                    connectionstyle: "arc3,rad=0.1",
                    from: "public_transport_bus",
                    to: "walk",
                    value: 10,
                    weight: 1,
                },
                {
                    arrows: "to",
                    arrowstyle: "simple",
                    connectionstyle: "arc3,rad=0.1",
                    from: "public_transport_bus",
                    to: "end",
                    value: 1,
                    weight: 1,
                },
                {
                    arrows: "to",
                    arrowstyle: "simple",
                    connectionstyle: "arc3,rad=0.1",
                    from: "public_transport_bus",
                    to: "public_transport_train",
                    value: 1,
                    weight: 1,
                },
                {
                    arrows: "to",
                    arrowstyle: "simple",
                    connectionstyle: "arc3,rad=0.1",
                    from: "public_transport_bus",
                    to: "public_transport_bus",
                    value: 1,
                    weight: 1,
                },
                {
                    arrows: "to",
                    arrowstyle: "simple",
                    connectionstyle: "arc3,rad=0.1",
                    from: "public_transport_bus",
                    to: "public_transport_change",
                    value: 1,
                    weight: 1,
                },
                {
                    arrows: "to",
                    arrowstyle: "simple",
                    connectionstyle: "arc3,rad=0.1",
                    from: "ship",
                    to: "end",
                    value: 1,
                    weight: 1,
                },
            ]),
            options: {
                nodes: {
                    font:{
                        size: 16,
                    },
                },
                configure: {
                    enabled: false,
                },
                edges: {
                    color: {
                        inherit: true,
                    },
                    smooth: {
                        enabled: true,
                        type: "dynamic",
                    },
                },
                interaction: {
                    dragNodes: true,
                    hideEdgesOnDrag: false,
                    hideNodesOnDrag: false,
                    zoomView:false
                },
                physics: {
                    barnesHut: {
                        avoidOverlap: 0,
                        centralGravity: 0.3,
                        damping: 0.09,
                        gravitationalConstant: -80000,
                        springConstant: 0.001,
                        springLength: 250,
                    },
                    enabled: true,
                    stabilization: {
                        enabled: true,
                        fit: true,
                        iterations: 1000,
                        onlyDynamicEdges: false,
                        updateInterval: 50,
                    },
                },
            },
        };
    },
    mounted(){
        let data = {nodes: this.nodes, edges: this.edges};
        let container = this.$refs.container;
        let network = new Network(container, data);
        network.setOptions(this.options);

    }
};
</script>

<style lang="scss" scoped>
</style>